name: Validate GitHub Actions

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@v1
